# .azure-pipelines.yml
# Sincroniza Azure DevOps (rama feature/22040_carga_mod_casos) -> GitHub (rama main)

trigger:
  branches:
    include:
      - feature/22040_carga_mod_casos

pool:
  vmImage: ubuntu-latest

variables:
  GIT_USER: "santiago_valenzuela"
  GIT_EMAIL: "svalenzuela@nexura.com"
  GITHUB_ORG: "anunezbedoya"
  GITHUB_REPO: "casos"

steps:
  - checkout: self
    clean: true
    persistCredentials: true  # importante para no perder auth del repo Azure

  # 1️⃣ Validar rama
  - script: |
      echo "Validando rama..."
      echo "Build.SourceBranchName = '$(Build.SourceBranchName)'"
      echo "Build.SourceBranch = '$(Build.SourceBranch)'"
      if [ "$(Build.SourceBranch)" != "refs/heads/feature/22040_carga_mod_casos" ]; then
        echo "❌ Solo la rama 'feature/22040_carga_mod_casos' puede sincronizarse con GitHub."
        exit 1
      fi
    displayName: "Validar rama origen"

  # 2️⃣ Configurar Git
  - script: |
      git config --global user.name "$(GIT_USER)"
      git config --global user.email "$(GIT_EMAIL)"
    displayName: "Configurar Git"

  # 3️⃣ Sincronizar con GitHub
  - script: |
      echo "Agregando remoto de GitHub..."
      git remote remove github || true
      git remote add github https://$(GITHUB_TOKEN_CASOS)@github.com/$(GITHUB_ORG)/$(GITHUB_REPO).git

      echo "Rama actual:"
      git branch --show-current || echo "(detached HEAD)"

      echo "Empujando commit actual (HEAD) hacia rama main en GitHub..."
      git push github HEAD:main --force

      echo "✅ Sincronización completada correctamente."
    env:
      GITHUB_TOKEN_CASOS: $(GITHUB_TOKEN_CASOS)
    displayName: "Sincronizar con GitHub"
